<a href="https://colab.research.google.com/github/dl-bk/AI_hw2/blob/master/module2/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [2]:
import numpy as np


#Завдання 1

Створіть масив з парними числами між 30 і 70

In [25]:
a = np.arange(30,71,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [28]:
b = np.linspace(0,1,10,endpoint=False)
print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [32]:
def funct(matrix):
  new_matrix = np.pad(matrix, ((1,1), (1,1)), mode='constant', constant_values=0)
  return new_matrix

matrix = np.arange(1,5)
matrix = np.reshape(matrix, (2,2))
matrix = funct(matrix)
print(matrix)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [33]:
float_matrix = matrix.astype(np.float32)
print(matrix.dtype)
print(float_matrix.dtype)

int64
float32


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [35]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5
x[x == var] = -1
print(x)
x[x > var] = -1
print(x)
x[x < var] = -1
print(x)

[ 1 -1  3  8  6 -1  7  4]
[ 1 -1  3 -1 -1 -1 -1  4]
[-1 -1 -1 -1 -1 -1 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [40]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

x = np.nan_to_num(X, nan=-1)
print(x)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [43]:
x = np.random.random((4,6))
x = np.reshape(x,(3,8))
print(x)

[[0.11878977 0.40751195 0.52126595 0.83342172 0.16548632 0.49824686
  0.86720932 0.7690538 ]
 [0.18996581 0.63394118 0.52748809 0.93281229 0.90416449 0.90705403
  0.61625169 0.02741667]
 [0.2895856  0.0391545  0.00144007 0.20745186 0.19191259 0.32352595
  0.17953176 0.08812481]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [49]:
ones_m = np.ones((3,4))
mean_ones = np.mean(ones_m, axis=0)
print(mean_ones)

[1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [34]:

a = np.random.rand(5,6)
sorted_idx = np.argsort(a[0])
sorted_a = a[:,sorted_idx]
rounded_a = np.round(sorted_a, 1)
print(rounded_a)


[[0.4 0.4 0.6 0.6 0.7 0.9]
 [0.6 0.  0.2 0.6 0.5 0.7]
 [0.5 0.4 1.  0.9 0.7 0.9]
 [0.7 1.  0.2 0.2 0.6 0.3]
 [0.7 0.4 0.1 0.  0.3 0.5]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [28]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

el = X[(X>3) & (X<6)]
print(el)

[4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом.

Після цього всі значення мають бути в межах [0, 1]

In [45]:
b = np.random.rand(5,6)
max_val = b.max(axis=0)
min_val = b.min(axis=0)
normalized_b = (b - min_val) / (max_val - min_val)
print(normalized_b)
print(b)

[[0.         0.11435691 0.8700342  0.7374423  0.02518318 0.63487614]
 [0.96976959 0.         0.         0.63987604 0.58156762 0.84712932]
 [0.11279202 0.59136059 1.         0.         0.         0.        ]
 [0.30027439 0.38793425 0.4336267  1.         0.52593997 1.        ]
 [1.         1.         0.80067191 0.92423933 1.         0.43024569]]
[[0.00948494 0.25532472 0.87837993 0.5541098  0.18408274 0.44521908]
 [0.2728101  0.20145779 0.408393   0.48159217 0.46078031 0.59339086]
 [0.04011178 0.48001356 0.94858663 0.00599443 0.1715588  0.00201852]
 [0.09101957 0.38419118 0.64263538 0.74925986 0.43311592 0.70010833]
 [0.28101867 0.67249995 0.84091087 0.69294958 0.66887244 0.30236865]]
